site_name: CD2 Reference
site_description: Unofficial reference docs for CD2 (and other resources).
theme: readthedocs
extra_css:
  - stylesheets/tables.css
markdown_extensions: 
  - attr_list
  - md_in_html
nav:
  - Introduction: index.md
  - FAQ: faq.md
  - The Basics of CD2: basics.md
  - Modules: modules.md 
  - (Module) Enemies / EnemiesNoSync: enemies.md 
  - (Module) Direct: direct.md 
  - (Module) WaveSpawners: wavespawners.md
  - Projectiles: projectiles.md
  - Mutators: mutators.md 
  - MEV, DEA and EEE: mev-dea.md
  - Tutorials: grouped_cooldowns.md
  - Resources: resources.md
